import { Product } from './types';

export const PRODUCTS: Product[] = [
  // Cables & Chargers
  {
    id: 'c1',
    name: 'VoltCharge GaN 65W Plug',
    description: 'Ultra-compact high wattage charger with dual USB-C ports. Equipped with intelligent GaN technology.',
    unitPrice: 4.80,
    packSize: 20,
    moq: 2,
    stock: 1200,
    rating: 4.9,
    icon: '🔌',
    category: 'cables',
    subCategory: 'CHARGERS',
    tags: ['GaN Fast', 'Dual Port', 'Best Seller'],
    image: require('../assets/images/Cable_And_Charger/c1.png'),
    images: [
      require('../assets/images/Cable_And_Charger/c1.png'),
      require('../assets/images/Cable_And_Charger/c2.png'),
    ],
    badge: 'offer',
    offerPercentage: 15,
  },
  {
    id: 'c2',
    name: 'ApexLink USB-C to C 100W',
    description: '1.2m double-braided nylon charging cable. E-marker chip certified for safe high-power delivery.',
    unitPrice: 1.50,
    packSize: 50,
    moq: 1,
    stock: 3500,
    rating: 4.8,
    icon: '⚡',
    category: 'cables',
    subCategory: 'CABLES',
    tags: ['100W PD', 'Braided', 'MFi Shielded'],
    image: require('../assets/images/Cable_And_Charger/c2.png'),
    images: [
      require('../assets/images/Cable_And_Charger/c2.png'),
      require('../assets/images/Cable_And_Charger/c3.png'),
    ],
    badge: 'best-seller',
  },
  {
    id: 'c3',
    name: 'MagPad 15W Wireless Disc',
    description: 'Magnetic wireless charging puck compatible with iPhone MagSafe. Sleek aluminum finish.',
    unitPrice: 6.20,
    packSize: 10,
    moq: 2,
    stock: 800,
    rating: 4.7,
    icon: '🔋',
    category: 'cables',
    subCategory: 'WIRELESS',
    tags: ['MagSafe compatible', 'Aluminum Body'],
    image: require('../assets/images/Cable_And_Charger/c3.png'),
    images: [
      require('../assets/images/Cable_And_Charger/c3.png'),
      require('../assets/images/Cable_And_Charger/c1.png'),
    ],
    badge: 'new-collection',
  },
  // Premium Cases
  {
    id: 'ca1',
    name: 'ShieldArmor Rugged Case',
    description: 'Military-grade drop-tested heavy duty protection case with integrated magnetic ring stand.',
    unitPrice: 2.10,
    packSize: 30,
    moq: 2,
    stock: 2400,
    rating: 4.9,
    icon: '🛡️',
    category: 'cases',
    subCategory: 'RUGGED',
    tags: ['Drop Proof', 'Built-in Stand'],
    image: require('../assets/images/PremimusCases/pc1.png'),
    images: [
      require('../assets/images/PremimusCases/pc1.png'),
      require('../assets/images/PremimusCases/pc2.png'),
      require('../assets/images/PremimusCases/pc5.png'),
    ],
    badge: 'best-seller',
  },
  {
    id: 'ca2',
    name: 'Liquid Silicone Comfort Case',
    description: 'Premium soft-touch case with microfiber interior lining. Scratch and fingerprint resistant.',
    unitPrice: 1.15,
    packSize: 50,
    moq: 2,
    stock: 5000,
    rating: 4.6,
    icon: '📱',
    category: 'cases',
    subCategory: 'SILICONE',
    tags: ['Soft Touch', 'Microfiber Lining', 'Multi-color'],
    image: require('../assets/images/PremimusCases/pc2.png'),
    images: [
      require('../assets/images/PremimusCases/pc2.png'),
      require('../assets/images/PremimusCases/pc3.png'),
      require('../assets/images/PremimusCases/pc6.png'),
    ],
    badge: 'offer',
    offerPercentage: 10,
  },
  {
    id: 'ca3',
    name: 'GlassBack Hybrid Crystal Shell',
    description: 'Crystal-clear protection featuring rigid tempered glass back panel and TPU shock bumper.',
    unitPrice: 1.80,
    packSize: 40,
    moq: 1,
    stock: 1600,
    rating: 4.7,
    icon: '💎',
    category: 'cases',
    subCategory: 'CLEAR',
    tags: ['Anti-Yellowing', 'Tempered Glass Back'],
    image: require('../assets/images/PremimusCases/pc3.png'),
    images: [
      require('../assets/images/PremimusCases/pc3.png'),
      require('../assets/images/PremimusCases/pc4.png'),
      require('../assets/images/PremimusCases/pc5.png'),
      require('../assets/images/PremimusCases/pc6.png'),
    ],
    badge: 'new-collection',
  },
  // Tempered Glass
  {
    id: 'g1',
    name: 'ProShield 9H Tempered Glass',
    description: '0.33mm ultra-thin 9H hardness tempered glass screen guard. Oleophobic coating for smudge resistance.',
    unitPrice: 0.45,
    packSize: 100,
    moq: 1,
    stock: 8500,
    rating: 4.8,
    icon: '👓',
    category: 'glass',
    subCategory: '9H GLASS',
    tags: ['9H Hardness', 'Anti-Fingerprint'],
    image: require('../assets/images/TemperedGlass/tg1.png'),
    images: [
      require('../assets/images/TemperedGlass/tg1.png'),
      require('../assets/images/TemperedGlass/tg2.png'),
    ],
    badge: 'best-seller',
  },
  {
    id: 'g2',
    name: 'PrivacyGuard 28° Anti-Spy Screen',
    description: 'Privacy filter screen protector block side views beyond 28 degrees. Includes alignment tool.',
    unitPrice: 0.90,
    packSize: 50,
    moq: 2,
    stock: 3000,
    rating: 4.9,
    icon: '🔒',
    category: 'glass',
    subCategory: 'PRIVACY',
    tags: ['Privacy Filter', 'Easy Install'],
    image: require('../assets/images/TemperedGlass/tg3.png'),
    images: [
      require('../assets/images/TemperedGlass/tg3.png'),
      require('../assets/images/TemperedGlass/tg2.png'),
    ],
    badge: 'offer',
    offerPercentage: 20,
  },
  // Audio & Wireless
  {
    id: 'a1',
    name: 'AcousticPods ANC Wireless',
    description: 'TWS earbuds featuring Active Noise Cancellation, Bluetooth 5.3, and 30-hour combined playback.',
    unitPrice: 12.50,
    packSize: 10,
    moq: 1,
    stock: 600,
    rating: 4.9,
    icon: '🎧',
    category: 'audio',
    subCategory: 'EARBUDS',
    tags: ['Active ANC', 'HD Audio', 'Long Battery'],
    image: require('../assets/images/Audio_And_Wireless/a1.png'),
    images: [
      require('../assets/images/Audio_And_Wireless/a1.png'),
      require('../assets/images/Audio_And_Wireless/a2.png'),
    ],
    badge: 'best-seller',
  },
  {
    id: 'a2',
    name: 'VoltLink Sports Neckband',
    description: 'Ergonomic neckband wireless earphones with magnetic earbuds and massive 40-hour battery capacity.',
    unitPrice: 3.80,
    packSize: 25,
    moq: 2,
    stock: 1400,
    rating: 4.7,
    icon: '🏃',
    category: 'audio',
    subCategory: 'NECKBANDS',
    tags: ['Magnetic Lock', '40h Music Time', 'Sweatproof'],
    image: require('../assets/images/Audio_And_Wireless/a3.png'),
    images: [
      require('../assets/images/Audio_And_Wireless/a3.png'),
      require('../assets/images/Audio_And_Wireless/a2.png'),
    ],
    badge: 'new-collection',
  },
];

export const CATEGORIES = [
  { id: 'cables', title: 'Cables & Chargers', count: '120+ Items', icon: '⚡', tagline: 'GaN Power & Fast Sync', desc: 'Certified charging bricks, multi-port power adapters, and double-braided nylon sync cables designed for wholesale distribution.', tags: ['MFi Approved', 'GaN Fast Tech', 'High Speed PD'], heroBg: require('../assets/images/Cable_And_Charger/cables_charger_hero.png') },
  { id: 'cases', title: 'Premium Cases', count: '340+ Designs', icon: '📱', tagline: 'Precision Fit & Heavy Protection', desc: 'Military-grade rugged armor covers, premium liquid silicone shells, and anti-yellowing crystal clear cases for all major flagships.', tags: ['Drop Rated', 'MagSafe Ready', 'Silicone Finish'], heroBg: require('../assets/images/PremimusCases/hero.png') },
  { id: 'glass', title: 'Tempered Glass', count: '80+ Models', icon: '🛡️', tagline: '9H Screen Shielding', desc: 'Premium privacy guard screen covers, ultra-clear 9H hardness tempered glass, and lens protectors with alignment fixtures.', tags: ['9H Tempered', 'Privacy Shield', 'Lens Ring Shield'], heroBg: require('../assets/images/TemperedGlass/tempered_hero.png') },
  { id: 'audio', title: 'Audio & Wireless', count: '90+ Products', icon: '🎧', tagline: 'HD Acoustics & Long Battery', desc: 'TWS active noise-cancelling earbuds, sweatproof wireless sports neckbands, and Bluetooth speaker catalog units.', tags: ['HD Audio Output', 'ANC Enabled', 'Sweatproof'], heroBg: require('../assets/images/Audio_And_Wireless/audio_wireless_hero.png') },
];

export const SLIDES = [
  {
    id: 1,
    title: 'Bulk Pricing System',
    desc: 'Unlock special volume tier rates for packs and boxes automatically.',
    icon: 'cash-outline',
    color: '#F59E0B',
    bg: 'bg-[#F59E0B]/10',
    border: 'border-[#F59E0B]/20',
  },
  {
    id: 2,
    title: 'Real-Time Stock Updates',
    desc: 'Browse current physical inventory live from our wholesale logistics hub.',
    icon: 'cube-outline',
    color: '#10B981',
    bg: 'bg-[#10B981]/10',
    border: 'border-[#10B981]/20',
  },
  {
    id: 3,
    title: 'Priority Logistic Network',
    desc: 'Same-day dispatch and tracker provisioning for authorized dealers.',
    icon: 'airplane-outline',
    color: '#3B82F6',
    bg: 'bg-[#3B82F6]/10',
    border: 'border-[#3B82F6]/20',
  },
  {
    id: 4,
    title: 'Direct Dealer Support',
    desc: 'Instant draft sharing and order fulfillment over WhatsApp direct channel.',
    icon: 'chatbubbles-outline',
    color: '#8B5CF6',
    bg: 'bg-[#8B5CF6]/10',
    border: 'border-[#8B5CF6]/20',
  },
];

export const getCategoryIconInfo = (id: string) => {
  switch (id) {
    case 'cables':
      return { icon: 'flash' as const, color: '#F59E0B', bg: 'bg-[#F59E0B]/10' };
    case 'cases':
      return { icon: 'phone-portrait' as const, color: '#06B6D4', bg: 'bg-[#06B6D4]/10' };
    case 'glass':
      return { icon: 'shield-checkmark' as const, color: '#10B981', bg: 'bg-[#10B981]/10' };
    case 'audio':
      return { icon: 'headset' as const, color: '#8B5CF6', bg: 'bg-[#8B5CF6]/10' };
    default:
      return { icon: 'grid' as const, color: '#3B82F6', bg: 'bg-[#3B82F6]/10' };
  }
};
